### ISSUE TITLE
Code to handle retrieval/sending communications between Raspberry Pi and Robotino

### ISSUE THREAD

**Issue by wwongandy** [WIT-BinBot-2020/pxt-binbot-wit-2020#11]
**I would like to**: Develop code to handle retrieval/sending communications between Raspberry Pi and Robotino

**So that I can**: Get the serial data from the Raspberry Pi and send instructions to move and monitor data in the Robotino using the given data and vice versa

**Context**: The project topology to handle the interaction between the MakeCode editor and the Robotino has changed from `MakeCode Microbit ))(( Microbit Gateway <-> Robotino` to `MakeCode Microbit ))(( Microbit Gateway <-> Raspberry Pi <-> Robotino`

**Comment by andyAndyA** [comment]
Done in [makecode-pi-comms](https://github.com/WIT-BinBot-2020/pxt-binbot-wit-2020/tree/makecode-pi-comms) branch.
