### ISSUE TITLE
Thread usage for each MakeCode instruction routing in Raspberry Pi Hub

### ISSUE THREAD

**Issue by wwongandy** [WIT-BinBot-2020/pxt-binbot-wit-2020#29]
**I would like to**: Start using threads for each MakeCode instruction routing in Raspberry Pi Hub

**So that I can**: Execute different MakeCode instructions at a time without blocking incoming instructions

**Context**: Currently upon a MakeCode instruction request, the current instruction will block any incoming ones from being executed until the current one is complete. In order to prevent it from blocking others, threads should be created for each MakeCode instruction task.

**Comment by jongillespie** [comment]
Not sure what progress you made on this... but an option is to have all the scripts manage their threads. That's how I formatted mine... Alternatively, we can do it in the main piHub... I have some simple examples you can use. Let's chat.

**Comment by wwongandy** [comment]
After our meeting this afternoon, we've concluded to have the usage of Thread modularised by everyone in their own separate components. So this issue will be closed for now.
